### ISSUE TITLE
AerialHell tool classes use unsafe attribute modifier code

### ISSUE THREAD

**Issue by Alexandra-Myers** [nicochart/AerialHell#1]
# https://github.com/Alexandra-Myers/Atlas-Combat/issues/23

> wait, why on earth is AerialHellPickaxeItem building it's own attribute modifiers? this is completely unnecessary and has been for, as far as I am aware, the entire history of Minecraft modding. I don't think you should be doing that. If you want to have those extra modifiers, I would instead suggest using this.defaultModifiers.put(Attributes.MOVEMENT_SPEED, new AttributeModifier(BASE_MOVEMENT_SPEED_UUID, "Weapon modifier", (double)movementSpeedIn, AttributeModifier.Operation.MULTIPLY_TOTAL)); for adding new attribute modifiers to the item. this.defaultModifiers will probably be private, so use an access transformer to gain access and get rid of the override for getAttributeModifiers

**Comment by Alexandra-Myers** [comment]
Basically, I would recommend just simply adding the attribute modifiers you need to the defaultModifiers field. In this case, my mod changed the return for DiggerItem.getAttackDamage(), but there is plenty of instances where using your own modifiers instead of defaultModifiers would be harmful

**Comment by Alexandra-Myers** [comment]
@nicochart @Cixon

**Comment by Cixon** [comment]
I appreciate this! Will relay to Nico

**Comment by nicochart** [comment]
Hello
It is impossible to "put" additional attributes in the defaultModifiers field because the map is an ImmutableMultimap.
Right now, I am trying to stop overriding the getAttributeModifiers method by accessing the defaultModifiers field (with an AT), and setting it to a cloned version with my additional attributes.
I hope it will fix the problem. (Currently waiting for Cixon testing)

**Comment by Cixon** [comment]
fixed in latest release i think

**Comment by nicochart** [comment]
It will be fixed in the next public release

**Comment by Alexandra-Myers** [comment]
> Hello It is impossible to "put" additional attributes in the defaultModifiers field because the map is an ImmutableMultimap. Right now, I am trying to stop overriding the getAttributeModifiers method by accessing the defaultModifiers field (with an AT), and setting it to a cloned version with my additional attributes. I hope it will fix the problem. (Currently waiting for Cixon testing)

Oh yeah, it uses ImmutableMultimap.Builder, which will produce an immutable multimap.
