### ISSUE TITLE
fabric category?

### ISSUE THREAD

**Issue by Rogenar** [nicochart/AerialHell#12]
although this mod is forge, why is it in the fabric category?

**Comment by nicochart** [comment]
Hello !
The mod is not in the Fabric category (as you can see below)
How do you see it in the Fabric category ?

![NotFabric](https://github.com/nicochart/AerialHell/assets/76011128/0139b369-c639-4ab1-a1b9-003e30a63d87)

**Comment by Rogenar** [comment]
I think this was a curseforge error and it has been fixed.
