### ISSUE TITLE
Ruby milk bucket

### ISSUE THREAD

**Issue by GoldenTotem** [nicochart/AerialHell#3]
Minecraft 1.16.5  Aerial 0.5.0
1. The name of ruby milk bucket is wrong. (Aerial tree milk bucket) 
2. Hold one ruby bucket, then click a cow, the ruby milk bucket will appear at the leftmost slot not original slot.
3. Ruby milk bucket doesn't work

**Comment by nicochart** [comment]
Fixed in Aerial Hell 1.16.5 version 0.5.1 (In [ this commit](https://github.com/nicochart/AerialHell/commit/d0dfc353582b689a037a7b7626facb06a01a44fb))

**Comment by nicochart** [comment]
Fixed in 1.16.5 version 0.5.2
(2. is fixed for 1.18+)
