### ISSUE TITLE
Chinese translation file for AerialHell 0.5.0

### ISSUE THREAD

**Issue by GoldenTotem** [nicochart/AerialHell#6]
I have translated this mod to Chinese. Language file zh_cn.json is in the zip file.

[zh_cn.zip](https://github.com/nicochart/AerialHell/files/12208665/zh_cn.zip)

Hoping that it may be helpful.

**Comment by nicochart** [comment]
Thanks ! It helps a lot !
Your translation will be added in the next update ;)

**Comment by nicochart** [comment]
Hello !
I've added your translation to the mod files, thank you again !

There is some missing translations, I added them in this commit : https://github.com/nicochart/AerialHell/commit/42537cf59a85285a64656599f3fa576870fd6aa2
(check the zh_cn.json file modifications)

If you don't mind, it would help me a lot (again) if you translate the latest additions ;)

**Comment by GoldenTotem** [comment]
> Hello ! I've added your translation to the mod files, thank you again !
> 
> There is some missing translations, I added them in this commit : [42537cf](https://github.com/nicochart/AerialHell/commit/42537cf59a85285a64656599f3fa576870fd6aa2) (check the zh_cn.json file modifications)
> 
> If you don't mind, it would help me a lot (again) if you translate the latest additions ;)

I haven't found the updated mod file on curseforge. Please give an update for 1.16.5, because I need it for my 1.16.5 modpack. 
Change a subject: if I can get the latest language file en_us.json, I can translate it easier. (Maybe I can do translation directly on github but I don't know how to do that  ╮（╯＿╰）╭  )

**Comment by nicochart** [comment]
The updated mod file is now available on Curseforge for 1.16.5 ;) The version is 0.5.1
You can do it directly on github by forking the repository, editing the file and pushing it in your fork, and then do a pull request
(it's easier to just edit the file and send it to me...)

If you want to discuss about the mod, about the translations or anything, please join the discord server : https://discord.gg/uQZYEqMySK
(I may close this issue someday)
