### ISSUE TITLE
Localization of Rarities

### ISSUE THREAD

**Issue by ObscuriaLithium** [nicochart/AerialHell#7]
I would like to ask you to add the names of the rarities to the localization files so that they can work with other mods. The key looks like this:
**rarity.{enum name}.name**, all lowercase.

![image-24.png](https://github.com/nicochart/AerialHell/assets/100697103/9bd6bd7f-3169-405c-8711-02d7469bf579)

**Comment by nicochart** [comment]
Hello !
The rarity localizations are now in the lang files for 1.20.4 (1.20.2) since version 0.6.6 (december 20, 2023)

**Comment by nicochart** [comment]
And they are now also available for 1.16.5 (version 0.5.2+)
